### ISSUE TITLE
Deal better with skipped #defines split across lines

### ISSUE THREAD

**Issue by kmsquire** [ihnorton/Clang.jl#102]
Most #defines seem to be handled correctly if they are split across lines.  However, in some cases, they are not.  

For example, https://github.com/vlfeat/vlfeat/blob/master/vl/mathop.h#L579-L596 is split across three lines in the output:

```julia
# Skipping MacroDefinition: VL_FAST_SQRT_UI ( T , SFX ) VL_INLINE T vl_fast_sqrt_ ## SFX ( T x ) \
{ T y = 0 ; T tmp = 0 ; int twice_k ; for ( twice_k = 8 * sizeof ( T ) - 2 ; twice_k >= 0 ; twice_k -= 2 ) { y <<= 1 ; /* y = 2 * y */ tmp = ( 2 * y + 1 ) << twice_k ; if ( x >= tmp ) { x -= tmp ; y += 1 ; } } return y ; \
}
```

**Comment by ihnorton** [comment]
Fixed by fecd91ad428b631ce7583eb26fcdaafcb3aa52ad.
