### ISSUE TITLE
clang_includes doesn't work?

### ISSUE THREAD

**Issue by stevengj** [ihnorton/Clang.jl#118]
I have
```
context = Clang.wrap_c.init(common_file="petsc.jl",
                            output_dir="petsc",
                            header_library=x->"libpetsc",
                            clang_includes=["/usr/local/include"],
                            clang_diagnostics=true)
context.headers = ["petsc.h"]
Clang.wrap_c.run(context)
```
and it gives me `error: error reading 'petsc.h'`.   If I explicitly give the header as `/usr/local/include/petsc.h`, however, it works.    Am I misunderstanding something?

**Comment by kmsquire** [comment]
For `VideoIO.jl`, I have

```julia
indexh         = joinpath(JULIA_HOME, "../include/clang-c/Index.h")
clang_includes = [joinpath(JULIA_HOME, "../lib/clang/3.3/include"), joinpath(dirname(indexh), "..")]

context = wrap_c.init(headers = av_headers,
                          common_file = joinpath(outdir, "$(library)_h.jl"),
                          clang_includes = clang_includes,
                          header_wrapped = check_use_header,
                          header_library = library,
                          header_outputfile = x->get_header_outfile(outdir,x),
                          rewriter = rewrite,
                          options = wrap_c.InternalOptions(true, true))
```

**Comment by stevengj** [comment]
So `clang_include` is actually the location of the Clang headers?  I thought it was equivalent to a `-I` flag.... the documentation is a little confusing here.

**Comment by ihnorton** [comment]
`clang_includes` is intended to be directories, equivalent to `-I`; `headers` is for the target headers. I've updated the example in d8ab8079.

> Why would it be necessary to specify the Clang header locations? Wouldn't that be set up in Pkg.build("Clang")?

At some point in the past it was necessary, although most likely due to a bug on my part.
