### ISSUE TITLE
Trouble building on OS X Yosemite

### ISSUE THREAD

**Issue by btello** [ihnorton/Clang.jl#138]
I'm having trouble building the Clang.jl package on OS X Yosemite.  It's complaining about not being able to find the std::terminate() function.  I added -v to g++ and this was the output from the Julia command line:

    julia> Pkg.build("Clang")
    INFO: Building Clang
    g++ -stdlib=libc++ wrapclang.cpp.o -rdynamic -shared -v -o libwrapclang.dylib -L/usr/local/Cellar/llvm/3.6.2/lib  -L/usr/local/Cellar/llvm/3.6.2/lib -lclang 
    Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
    Target: x86_64-apple-darwin14.5.0
    Thread model: posix
     "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -export_dynamic -dynamic -dylib -arch x86_64 -macosx_version_min 10.10.0 -o libwrapclang.dylib -L/usr/local/Cellar/llvm/3.6.2/lib -L/usr/local/Cellar/llvm/3.6.2/lib wrapclang.cpp.o -lclang -lc++ -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.1.0/lib/darwin/libclang_rt.osx.a
    Undefined symbols for architecture x86_64:
      "std::terminate()", referenced from:
          ___clang_call_terminate in wrapclang.cpp.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [libwrapclang.dylib] Error 1
    ================================[ ERROR: Clang ]=================================
    
    failed process: Process(`make`, ProcessExited(2)) [2]
    while loading /Users/brxxxx/.julia/v0.3/Clang/deps/build.jl, in expression starting on line 17
    
    =================================================================================
    
    ================================[ BUILD ERRORS ]=================================

    WARNING: Clang had build errors.

     - packages with build errors remain installed in /Users/brxxxx/.julia/v0.3
     - build the package(s) and all dependencies with `Pkg.build("Clang")`
     - build a single package by running its `deps/build.jl` script

    ===============================================================================

Any help you can offer is greatly appreciated.

**Comment by stemann** [comment]
This seems to work on OS X. Insert:
```
  LIBS += -stdlib=libstdc++ -lc++
```
in line 45 in deps/src/Makefile

**Comment by bjarthur** [comment]
this change fixes el capitan as well.  see PR https://github.com/ihnorton/Clang.jl/pull/149
