### ISSUE TITLE
LoadError: failed process: Process(`which llvm-config`, ProcessExited(1)) [1]

### ISSUE THREAD

**Issue by mmacedoeu** [ihnorton/Clang.jl#144]
Ubuntu Willy with llvm `1:3.6-26ubuntu1` installed

```
julia> Pkg.add("Clang")
INFO: Cloning cache of Clang from git://github.com/ihnorton/Clang.jl.git
INFO: Cloning cache of DataStructures from git://github.com/JuliaLang/DataStructures.jl.git
INFO: Installing Clang v0.0.5
INFO: Installing DataStructures v0.3.13
INFO: Building Clang
================================[ ERROR: Clang ]================================

LoadError: failed process: Process(`which llvm-config`, ProcessExited(1)) [1]
while loading /home/macedo/.julia/v0.4/Clang/deps/build.jl, in expression starting on line 10

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Clang had build errors.

 - packages with build errors remain installed in /home/macedo/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Clang")`
 - build a single package by running its `deps/build.jl` script

================================================================================
```

**Comment by yuyichao** [comment]
install `llvm-*-dev` and `clang`

**Comment by mmacedoeu** [comment]
Now with llvm-dev and clang i had this:

julia> Pkg.build("Clang")
INFO: Building Clang
================================[ ERROR: Clang ]================================

LoadError: UndefVarError: DL_LOAD_PATH not defined
while loading /home/macedo/.julia/v0.4/Clang/deps/build.jl, in expression starting on line 14

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Clang had build errors.

 - packages with build errors remain installed in /home/macedo/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Clang")`
 - build a single package by running its `deps/build.jl` script

================================================================================

**Comment by yuyichao** [comment]
There isn't a new release for the 0.4 compatible version yet. @ihnorton. I'll tag one tomorrow if you are busy.

In the mean time, @mmacedoeu try `Pkg.checkout("Clang")`.

P.S. Please also quote your code, it's much easier to read that way. (see my edit of your comments)

**Comment by mmacedoeu** [comment]
I also installed package libclang-dev 1:3.6-26ubuntu1 as I could see on README it was required.

julia> Pkg.add("Clang")
INFO: Nothing to be done
