### ISSUE TITLE
clang v3.6.2 supported?

### ISSUE THREAD

**Issue by bjarthur** [ihnorton/Clang.jl#148]
the Clang.jl README says >=3.1 is supported.  is there an upper limit?  i ask because  on OS X El Capitan with Julia 0.4.0 distributed and Homebrew LLVM 3.6.2, i get a ```'clang-c/Index.h' file not found``` error.  (3.4.2 kinda works, but see https://github.com/ihnorton/Clang.jl/issues/147.)

```
julia> ENV["LLVM_CONFIG"]="/usr/local/Cellar/llvm/3.6.2/bin/llvm-config"
"/usr/local/Cellar/llvm/3.6.2/bin/llvm-config"

julia> Pkg.add("Clang")
INFO: Initializing package repository /Users/arthurb/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Installing Clang v0.1.0
INFO: Installing Compat v0.7.7
INFO: Installing DataStructures v0.3.13
INFO: Installing Docile v0.5.19
INFO: Building Clang
g++ wrapclang.cpp -fPIC -c -o wrapclang.cpp.o -I/usr/local/Cellar/llvm/3.6.2/include -g -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fPIC 
wrapclang.cpp:7:10: fatal error: 'clang-c/Index.h' file not found
#include "clang-c/Index.h"
         ^
1 error generated.
make: *** [wrapclang.cpp.o] Error 1
================================[ ERROR: Clang ]================================

LoadError: failed process: Process(`make`, ProcessExited(2)) [2]
while loading /Users/arthurb/.julia/v0.4/Clang/deps/build.jl, in expression starting on line 19

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Clang had build errors.

 - packages with build errors remain installed in /Users/arthurb/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Clang")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated

julia> 
```

**Comment by yuyichao** [comment]
Do you have the libclang headers installed? See https://github.com/Gnurou/kdevelop/issues/10 for example.

**Comment by bjarthur** [comment]
i did a search on the error msg too, and found that very same page.  notice that to fix it they had to downgrade from clang 3.3 to 3.2.

i do have headers installed, but there is no clang-c directory.  there is an llvm-c directory, but it doesn not contain an Index.h file:

```
$ ls /usr/local/Cellar/llvm/3.6.2/include/llvm-c/
Analysis.h		Disassembler.h		LinkTimeOptimizer.h	Target.h
BitReader.h		ExecutionEngine.h	Linker.h		TargetMachine.h
BitWriter.h		IRReader.h		Object.h		Transforms/
Core.h			Initialization.h	Support.h		lto.h
```

**Comment by yuyichao** [comment]
That still sounds like a installation problem.

The file certainly exist on my ArchLinux clang 3.7.0 and also on ubuntu libclang-3.6-dev and is also in the pre-built tarball for ubuntu 15.04 from llvm's site (I didn't check other binaries there but I imagine they all have this file).

**Comment by ihnorton** [comment]
Yes, I've used this up to llvm 3.8.

**Comment by bjarthur** [comment]
it was indeed an install problem.  please consider https://github.com/ihnorton/Clang.jl/pull/149 to make it easier for others.
