### ISSUE TITLE
Generating safer wrapper for pointer arguments

### ISSUE THREAD

**Issue by yuyichao** [ihnorton/Clang.jl#152]
For a c function like `void foo(bar*);` `Clang.jl` generates wrapper that looks like

```
function foo(arg1::Ptr{bar})
    ccall((:foo, lib), Void, (Ptr{bar},), arg1)
end
```

However, this is dangerous since it bypasses the GC root mechanism for `ccall` and encourage people to use `ccall` in the wrong way. As an example, I noticed this since I was checking out `NIDAQ.jl`, the correct way to implement [this](https://github.com/JaneliaSciComp/NIDAQ.jl/blob/8d99d65467fbba80844862838b42e48b1fb3f337/src/functions_V15.1.1.jl#L52) function is

```jl
function DAQmxLoadTask(taskName,taskHandle)
    ccall((:DAQmxLoadTask,NIDAQmx),int32,(Cstring,Ptr{TaskHandle}),taskName,taskHandle)
end
```

And the caller is supposed to pass in a julia string as the input and a `Ref{TaskHandle}()` as the output. There might be adaptor method that can't easily be generated (`unsafe_convert` that depend on the higher level abstraction used) but the function generated should at least be compatible with it (by not including the type constraint on the method definition) and the document should be clear that what additional functions the user need to implement in order to use these generated wrappers correctly.

The `Cstring` vs `Ptr{UInt8}` could be a little subtle since the function doesn't always want a null-terminated string but using `Cstring` instead of `Ptr{UInt8}` should generally be safer. The user will notice if he want `Ptr{UInt8}` instead of `Cstring` but the other way around can only be discovered by hitting weird runtime failure.

**Comment by ihnorton** [comment]
Thanks for *pointing* this out, will merge the PR soon.
