### ISSUE TITLE
Feature (or documentation) request: a more generic, portable way of dealing with errors like "fatal error: 'stddef.h' file not found"

### ISSUE THREAD

**Issue by ackalker** [ihnorton/Clang.jl#163]
Trying to use Clang.jl on Arch Linux, clang 3.7.1-1, i'm getting the dreaded error mentioned above:

``` julia
julia> using Clang.cindex

julia> topcu = cindex.parse_header("/usr/include/stdio.h", args = ["-v"])
clang version 3.7.1 (tags/RELEASE_371/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /../lib/gcc/x86_64-unknown-linux-gnu/5.3.0
Found candidate GCC installation: /../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-unknown-linux-gnu/5.3.0
Selected GCC installation: /../lib64/gcc/x86_64-unknown-linux-gnu/5.3.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
ignoring nonexistent directory "../lib/clang/3.7.1/include"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /usr/include
End of search list.
/usr/include/stdio.h:33:11: fatal error: 'stddef.h' file not found
CLCursor (Clang.cindex.TranslationUnit) /usr/include/stdio.h
```

Naturally I have read the FAQ entry on libclang tooling, so I know that I have to supply the correct path to Clang's built-in include files.

While looking at Clang's sources, in particular [this line](https://github.com/llvm-mirror/clang/blob/76ace1ff8d66981fcf542fb62e0539b203111479/test/lit.cfg#L220), I came up with the following: why not retrieve the correct include path automatically?

Reworking the example in `README.md`, I came up with

``` julia
julia> incpath = chomp(readall(`clang -print-file-name=include`))
"/usr/bin/../lib/clang/3.7.1/include"

julia> topcu = cindex.parse_header("/usr/include/stdio.h", args = ["-nobuiltininc", "-I$incpath"])
CLCursor (Clang.cindex.TranslationUnit) /usr/include/stdio.h

julia> cu = cindex.search(topcu, "printf")[1]
CLCursor (Clang.cindex.FunctionDecl) printf(const char *restrict, ...)
```

(Note: I added the `-nobuiltininc` flag to prevent the tool from picking up any stray header files stored in a `../lib/clang/...` directory which could happen to exist alongside the current directory.)
I was wondering if this could somehow be incorporated into this package's build process, or at least added to the documentation for use by wrapper creators.
This should make non-portable, highly platform/version specific hacks like [this](https://github.com/JuliaLang/Sundials.jl/blob/252337d9f434f1bb9491fa55dbce9df5e406076f/src/wrap_sundials.jl#L36-L40) unnecessary.

Any comments or suggestions are very welcome.

**Comment by Gnimuc** [comment]
this could be fixed by #210 since we now use BB2 to install those headers in the same place. there is an exported variable `LLVM_INCLUDE` for this purpose.
