### ISSUE TITLE
LoadError: failed process: Process(`which llvm-config`, ProcessExited(1)) [1]

### ISSUE THREAD

**Issue by femtotrader** [ihnorton/Clang.jl#165]
Hello,

I'm trying to build Clang under Mac OS X 10.10.5

```
julia> Pkg.build("Clang")
INFO: Building Clang
================================[ ERROR: Clang ]================================

LoadError: failed process: Process(`which llvm-config`, ProcessExited(1)) [1]
while loading /Users/scls/.julia/v0.4/Clang/deps/build.jl, in expression starting on line 12

================================================================================

==============================================[ BUILD ERRORS ]==============================================

WARNING: Clang had build errors.

 - packages with build errors remain installed in /Users/scls/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Clang")`
 - build a single package by running its `deps/build.jl` script

============================================================================================================
```

```bash
$ llvm-config
bash: llvm-config: command not found
```

```bash
$ llvm-gcc --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

I don't know how to fix this.

Any idea ?

Kind regards

**Comment by kmsquire** [comment]
@femtotrader, `llvm-gcc` is likely just a link to `clang`:

```
$ ls -l $(which llvm-gcc)
lrwxr-xr-x 1 root wheel 5 Dec  6  2014 /usr/bin/llvm-gcc -> clang
```

It is true that Apple does use llvm for some system components (e.g., compiling device drivers), but AFAIK, that isn't generally usable, so you'll have to install it another way, most likely by following the notes in the [Prerequisites](https://github.com/ihnorton/Clang.jl#prerequisites), which means compiling julia yourself and enabling `BUILD_LLVM_CLANG`.

I just noticed `brew` has a version of llvm, but it's on v3.6, which isn't supported on Julia.  If you're adventurous, you could try installing with `brew` and `--HEAD`, but that  probably won't work on anything but the latest master (and maybe not then).

**Comment by rawlik** [comment]
I have successfully installed Clang on OSX using `llvm` from `brew` (which is v3.8 by now).
(commands for `fish` shell, for `bash` use `export`)
```fish
brew install llvm
set -x CPPFLAGS -I/usr/local/opt/llvm/include
set -x LDFLAGS -L/usr/local/opt/llvm/lib
set -x PATH /usr/local/opt/llvm/bin/ $PATH
set -x LD_LIBRARY_PATH /usr/local/opt/llvm/lib/
julia -e 'Pkg.add("Clang")'
```
