### ISSUE TITLE
using Clang fails: ERROR: LoadError: ReadOnlyMemoryError()

### ISSUE THREAD

**Issue by mrquant** [ihnorton/Clang.jl#175]
Hi, I compiled julia with BUILD_LLVM_CLANG=1 and installed Clang.jl, but when I try to import the package it fails. This is the stack trace:

`
julia> Pkg.build("Clang")
INFO: Building Clang

julia> using Clang
ERROR: LoadError: LoadError: ReadOnlyMemoryError()
Stacktrace:
 [1] dlopen_e(::String, ::UInt32) at ./libdl.jl:110
 [2] find_library(::Array{String,1}, ::Array{String,1}) at ./libdl.jl:135
 [3] include_from_node1(::String) at ./loading.jl:539
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:539
 [6] eval(::Module, ::Any) at ./boot.jl:235
 [7] require(::Symbol) at ./loading.jl:453
while loading /home/carlos/.julia/v0.6/Clang/src/../deps/ext.jl, in expression starting on line 6
while loading /home/carlos/.julia/v0.6/Clang/src/Clang.jl, in expression starting on line 6
`

`julia> versioninfo()
Julia Version 0.6.0-pre.beta.295
Commit dc907c7 (2017-04-24 04:37 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)`

libclang looks reachable as shared library:

`julia> Libdl.dlopen("libclang")
Ptr{Void} @0x000000000429a300
`
Any idea? Thanks.

**Comment by ihnorton** [comment]
Could you try dlopen'ing `libwrapclang.so`? I believe that's what is failing there.

**Comment by mrquant** [comment]
@ihnorton that worked! I placed libwrapclang on the path and now is working! thanks!

**Comment by ExpandingMan** [comment]
Which path did you add it to?

I'm very confused as to why this error gets thrown.  If from the REPL you do
```julia
Libdl.find_library(["libwrapclang"], [joinpath(Pkg.dir("Clang"),"deps","usr","lib"])
```
it works just fine.  But the same line running from `ext.jl` throws the `ReadOnlyMemoryError`.

Instead, I did
```julia
const libwci_file = joinpath(Pkg.dir("Clang"),"deps","usr","lib","libwrapclang.so")
const libwci = isfile(libwci_file) ? libwci_file : ""
```
which seems to work.  Of course it's now OS dependent because of the `.so`, so it's not a proper fix.

**Comment by ihnorton** [comment]
I reworked some of this. Comment/reopen if necessary.
