### ISSUE TITLE
KeyError: key 119 not found

### ISSUE THREAD

**Issue by jgoldfar** [ihnorton/Clang.jl#176]
Running Clang.jl (master) on a relatively large C codebase, I keep getting the following error:
```
INFO: Error thrown. Last cursor available in Clang.wrap_c.debug_cursors
ERROR: LoadError: KeyError: key 119 not found
 in getindex(::Dict{Int32,Any}, ::Int32) at ./dict.jl:688
 in getTypedefDeclUnderlyingType(::Clang.cindex.TypedefDecl) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/cindex/base.jl:91
 in #wrap#35(::String, ::Function, ::Clang.wrap_c.WrapContext, ::DataStructures.OrderedDict{Symbol,Clang.wrap_c.ExprUnit}, ::Clang.cindex.TypedefDecl) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/wrap_c.jl:501
 in wrap(::Clang.wrap_c.WrapContext, ::DataStructures.OrderedDict{Symbol,Clang.wrap_c.ExprUnit}, ::Clang.cindex.TypedefDecl) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/wrap_c.jl:478
 in wrap_header(::Clang.wrap_c.WrapContext, ::Clang.cindex.TranslationUnit, ::String, ::Array{Any,1}) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/wrap_c.jl:680
 in run(::Clang.wrap_c.WrapContext) at /Users/jgoldfar/Documents/misc/env/bin/julia/.julia/v0.5/Clang/src/wrap_c.jl:799
```

Not sure how to proceed... Any direction would be appreciated!

**Comment by ihnorton** [comment]
Looks like a missing mapping for types in a newer version of libclang. Please try adding these constants:

https://github.com/llvm-mirror/clang/blob/b6ac2f9d15b1ef6b9e329f6d262487a8c6e93244/include/clang-c/Index.h#L3033-L3043

to the definitions under `baremodule TypeKind` in `src/cindex/defs.jl` (hopefully that's the only thing required, but could be more involed if those types need special handling).

**Comment by jgoldfar** [comment]
Branch with the above change and some other hacks to get Clang.jl to wrap igraph here:

https://github.com/jgoldfar/Clang.jl/tree/wrap-igraph

As far as I can tell, nothing is explicitly broken in the wrapper output, but I have no idea about the "correctness" of the changes; I'm no Clang expert (I have some reading to do...) Feel free to close this issue...

**Comment by ihnorton** [comment]
LGTM, mind to make a pull-request?
