### ISSUE TITLE
CXLinkageKind not defined

### ISSUE THREAD

**Issue by bjarthur** [ihnorton/Clang.jl#181]
julia 0.6, llvm 3.9.1 (via Homebrew on OSX), master branch of Clang.jl:

```
$ export PATH=/usr/local/Cellar/llvm\@3.9/3.9.1_1/bin:$PATH

julia> using Clang

ERROR: LoadError: LoadError: LoadError: UndefVarError: CXLinkageKind not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:569
 [6] eval(::Module, ::Any) at ./boot.jl:235
 [7] _require(::Symbol) at ./loading.jl:483
 [8] require(::Symbol) at ./loading.jl:398
while loading /Users/arthurb/.julia/v0.6/Clang/src/cindex/base.jl, in expression starting on line 64
while loading /Users/arthurb/.julia/v0.6/Clang/src/cindex.jl, in expression starting on line 25
while loading /Users/arthurb/.julia/v0.6/Clang/src/Clang.jl, in expression starting on line 7
```

**Comment by bjarthur** [comment]
it's defined in Clang/src/gencindex.jl, but this file is never included by src/Clang.jl or any of it's includes so far as i can tell (via a grep -r gencindex *).  how is this supposed to work?

**Comment by ihnorton** [comment]
I guess 0.6 is stricter! From what I can tell, those weren't ever defined or used. I have a branch with some other fixes that I'll push as soon as I get a chance to finish.

**Comment by bjarthur** [comment]
thanks!  any idea on the time frame?  i'd like to update NIDAQ.jl to the latest NI-DAQmx drivers and need Clang.jl to do so.  folks are anxious about julia 0.6!
