### ISSUE TITLE
more $ in wrap_c output

### ISSUE THREAD

**Issue by bjarthur** [ihnorton/Clang.jl#186]
thanks for https://github.com/ihnorton/Clang.jl/issues/182.  still having problems though with `wrap_c()`.

here is my `test.h`:

```
typedef signed char int8;
```

this results in:

```
$(Expr(:typealias, :int8, :UInt8))
```

**Comment by ihnorton** [comment]
This and the other one are due to some rework of expression printing in base where `typealias` was left out (maybe due to deprecation). So just use the new thing, which should work fine on 0.5 too I think.
