### ISSUE TITLE
`wrap_c.wrap_c_headers` not found

### ISSUE THREAD

**Issue by JeffreySarnoff** [ihnorton/Clang.jl#207]
Has this been replaced with another function/sequence?

**Comment by Gnimuc** [comment]
`wrap_header`? I guess

**Comment by JeffreySarnoff** [comment]
from [C Wrapper Generator](https://clangjl.readthedocs.io/en/latest/wrap_c.html) in docs
```
context = wrap_c.init()

headers = ["all.h", "your.h", "headers.h"]
wrap_c.wrap_c_headers(context, headers)
```

I'm looking for something with that signature.

**Comment by Gnimuc** [comment]
The doc has not been updated for a long time, so it's better to refer to some real-world examples like this https://github.com/JuliaWeb/LibCURL.jl/blob/master/gen/generate.jl.

X-ref: https://github.com/ihnorton/Clang.jl/issues/117

**Comment by JeffreySarnoff** [comment]
thank you
