### ISSUE TITLE
Use BinaryProvider for All OSes

### ISSUE THREAD

**Issue by btaidm** [ihnorton/Clang.jl#211]
This would take a lot of the guess work out of making sure that LLVM is installed. It would also allow the libclang used to match julia's LLVM.

**Comment by ihnorton** [comment]
Yes. See comments on https://github.com/ihnorton/Clang.jl/pull/210
I believe we are waiting for an upstream fix.

**Comment by Gnimuc** [comment]
hi, @btaidm, I just released Julia 1.0-compatible libclang binaries, you could give it a try now:
```
add Clang#6b1bb2b53becb1bba615315172ab8e1ff16dada3
```
