### ISSUE TITLE
Generate C wrappers for inline functions

### ISSUE THREAD

**Issue by ihnorton** [ihnorton/Clang.jl#34]
Goal is to work with packaged versions of various C++ libraries. No recompilation of the library should be required. Nothing should be needed on the Julia side except the headers.

- [ ] verify that the table layout is generated correctly by clang in light of inlining (vs gcc)
- [ ] function to resolve header includes to real paths
- [ ] generate C wrapper for all public inline functions.

**Comment by victorsndvg** [comment]
HI @ihnorton ,

any news on this?

I would like to automatically wrap some headers that contain `static inline` functions and I don't know where to start. Now I'm checked if `isinlined()` to ignore them ... but is not what I want.

How can I deal with `static inline` functions? are currently supported?

Thanks in advance!

**Comment by Gnimuc** [comment]
@victorsndvg wrapping C++ libraries are not supported, please try Cxx.jl(only support Julia-v1.3- for now) instead.

**Comment by victorsndvg** [comment]
@Gnimuc , in thiscase I'm dealing with a C library with inlined functions, not C++ library.

Such functions are `inlined` and implemented in headers, see the example hear:
https://github.com/cburstedde/libsc/blob/7089d44934f34b60d6f63dded2cf774eebbfe1c9/src/sc_containers.h#L458

The library does not contain those symbols. How can I call them from julia?

**Comment by Gnimuc** [comment]
In C, `static` marks that function to be "private", which means the library author doesn't allow users to use it intentionally. If you'd like to walk around that, I think you could always add a wrapper C function with the same signature and recompile. 

For this particular function, it looks like it just does some basic pointer arithmetics, maybe you could use Julia's `unsafe_load`/`unsafe_wrap` to implement the same functionality.

**Comment by victorsndvg** [comment]
Ok @Gnimuc , I think I caught how to deal with it.

Thanks for your quick response. It has been very helpful!

**Comment by yuyichao** [comment]
`static` aren't private in that the function isn't intended to be used by the user. It just mean that the function won't be part of the ABI of the library but is otherwise fully usable by the user.

Using that, however, always require the equivalence of a C compiler, and that's not in the current scope of `Clang.jl`.

**Comment by victorsndvg** [comment]
Yeah, I understand @yuyichao .

Then I would like to know whether a declaration is static or not from Clang.jl, is this possible?
I can check if it `isinlined`, but I don't see any function similar to  `isstatic`.

Very helpful.
Thanks in advance!
