### ISSUE TITLE
Small details from wrapping libcudart

### ISSUE THREAD

**Issue by timholy** [ihnorton/Clang.jl#48]
This is really just an FYI. I was able to get everything working (at least, at the level of being able to `include` the files without error---I haven't actually tested code yet) by adding following manually-generated file:

```
# These are all used only inside Ptrs
typealias cudaArray Void
typealias cudaMipmappedArray Void
typealias CUstream_st Void
typealias CUevent_st Void
typealias cudaGraphicsResource Void

include("libcudart_h.jl")
typealias cudaError_t cudaError
# Important! Delete or comment-out functions in libcudart.jl using
# cudaResourceDesc
```

Explanations:
- During wrapping, I see clear messages like `WARNING: Skipping empty struct: "cudaArray"`. EDIT: this makes it easy to figure out which ones I needed to add a `typealias ... Void` to, once I knew the pattern.
- The issue with `cudaResourceDesc` is that it has `union` members that are structs. It was converted as:

```
type cudaResourceDesc
    resType::cudaResourceType
    res::
end
```

I had to comment it out in `libcudart_h.jl`, and then comment out any functions using it in `libcudart.jl`.

Those are pretty minimal manual interventions. Quite an amazing tool, Isaiah!

**Comment by Gnimuc** [comment]
It's worth to try the package again if you'd like to generate wrappers for other c libs ;)
